# Site settings
title: Small & Simple Things
email: tomdeforest@gmail.com
description: "By Tom DeForest"
baseurl: ""
url: "http://tomdeforest.github.io"

# Build settings
markdown: kramdown
permalink: none
