#-------------------------------
# Site Settings
title: Small & Simple Things
logo: "/images/silcrow.png" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/silcrow.png"
description: Small & Simple Things by Tom DeForest
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author_name: Tom DeForest


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"

#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-instagram", link: "https://www.instagram.com/smallandsimplethings.org_/"}
- {icon: "fa-brands fa-dribbble", link: "https://dribbble.com/smallandsimple"}

# Example of adding a new link to the header and footer - {icon: "fa-brands fa-youtube", link: "https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: <span><i>Small & Simple Things</i></span> # Add the "span" tag to highlight text.
  hero_description: by Tom DeForest 
  hero_image: "/images/paper-art-waves.jpg"
  hero_button_contact: Get In Touch
  hero_button_about: About Me


#-------------------------------
# Projects Settings
section_projects_title: 👨🏻‍💻 Selected Works


#-------------------------------
# Testimonials Section
section_testimonial_title: 🙂 What Clients Say

testimonial_items:
  - name: "Carla Kenter"
    image: "/images/client-1.jpg"
    designation: "Professional Artist"
    link: "https://twitter.com/"
    content : "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"

  - name: "Kierra Botosh"
    image: "/images/client-2.jpg"
    designation: "Growth & Community"
    link: "https://facebook.com/"
    content : "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"

  - name: "Randy Herwitz"
    image: "/images/client-3.jpg"
    designation: "Executive Assistant"
    link: "https://twitter.com/"
    content : "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"

  - name: "Hanna Franci"
    image: "/images/client-4.jpg"
    designation: "Product Designer"
    link: "https://twitter.com/"
    content : "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus"


#-------------------------------
# Blog Section
section_blog_title: 📚 Read Latest Posts
#-------------------------------


# Tags Section
section_tags_title: ✌️ Explore Topics


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: true
  mailchimp_title: Get interesting news
  mailchimp_identifier: smallandsimplethings.us21.list-manage.com/subscribe/post?u=0c40591b2049de5edad5e36ab&amp;id=3a7101c0ee&amp;f_id=004d5ae1f0 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp_input_text: Enter your email address
  mailchimp_background_image: /images/paper-art-sakura.jpg

#-------------------------------
# Footer Settings
footer_description: I’m Tom DeForest, and I'm glad you're here. Through curiosity and collaboration I find and amplify good.


#-------------------------------
# Footer Navigation Settings
footer_menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Projects"
      url: "/projects/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"

#-------------------------------
# Contact Settings
contact:
  email: smallandsimplethings@proton.me # Add your form_id
  description: Simpler comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id